PATH:
  DATASET: ./data/datasets/samson_dataset.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  BETA: 5000.0
  COL: 95
  COSLR_RATE: 0.01
  DATASET: samson
  MODEL_NAME: swin_transformer
  DIM: 60
  EPOCH: 600
  GAMMA: 3.0e-06
  INIT: False
  L: 156
  LR: 0.01
  ORDER_ABD: &id001
  - 0
  - 1
  - 2
  ORDER_ENDMEM: *id001
  P: 3
  PATCH: 5
  WEIGHT_DECAY_PARAM: 4.0e-05
