PATH:
  DATASET: ./data/datasets/jasper_dataset.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  BATCH: 20
  BETA: 5000.0
  COL: 100
  COSLR_RATE: 0.01
  DATASET: jasper
  DIM: 36
  EPOCH: 60000
  GAMMA: 0.05
  INIT: True
  L: 198
  LR: 0.01
  MODEL_NAME: swin_transformer
  ORDER_ABD: &id001
  - 1
  - 0
  - 3
  - 2
  ORDER_ENDMEM: *id001
  P: 4
  PATCH: 5
  WEIGHT_DECAY_PARAM: 0.0
