PATH:
  DATASET: ./data/datasets/synthetic_RationalGF.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  BATCH: 20
  BETA: 5000.0
  COL: 128
  COSLR_RATE: 0.01
  DATASET: synthetic_RationalGF
  DIM: 80
  EPOCH: 200
  GAMMA: 0.05
  INIT: true
  L: 228
  LR: 0.001
  MODEL_NAME: cnn_vit
  ORDER_ABD: &id001
  - 0
  - 1
  - 2
  - 3
  - 4
  ORDER_ENDMEM: *id001
  P: 5
  PATCH: 4
  WEIGHT_DECAY_PARAM: 4.0e-05
