PATH:
  DATASET: ./data/datasets/jasper_dataset.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  BATCH: 20
  BETA: 5000.0
  COL: 100
  COSLR_RATE: 0.1
  DATASET: jasper
  DIM: 100
  EPOCH: 2000
  GAMMA: 0.05
  INIT: True
  L: 198
  LR: 0.006
  MODEL_NAME: cnn_vit
  ORDER_ABD: &id001
  - 1
  - 0
  - 2
  - 3
  ORDER_ENDMEM: *id001
  P: 4
  PATCH: 5
  WEIGHT_DECAY_PARAM: 4.0e-05
