PATH:
  DATASET: ./data/datasets/synthetic_MaternGFSNR30.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
  TIME: 20221021-13-11-45
TRAINING:
  BATCH: 20
  BETA: 5000.0
  COL: 128
  COSLR_RATE: 0.01
  DATASET: synthetic_MaternGFSNR30.mat
  DIM: 48
  EPOCH: 20000
  GAMMA: 0.05
  INIT: true
  L: 228
  LR: 0.001
  MODEL_NAME: swin_transformer
  ORDER_ABD:
  - 0
  - 1
  - 2
  - 3
  - 4
  ORDER_ENDMEM:
  - 0
  - 1
  - 2
  - 3
  - 4
  P: 5
  PATCH: 4
  WEIGHT_DECAY_PARAM: 0.0
