PATH:
  DATASET: ./data/datasets/samson_dataset.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  BETA: 5000.0
  COL: 95
  LR: 0.0016
  COSLR_RATE: 0.8
  DATASET: samson
  MODEL_NAME: swin_transformer
  DIM: 30
  EPOCH: 40000
  GAMMA: 3.0e-02
  INIT: True
  L: 156

  ORDER_ABD: &id001
  - 0
  - 1
  - 2
  ORDER_ENDMEM: *id001
  P: 3
  PATCH: 5
  WEIGHT_DECAY_PARAM: 0.0
