PATH:
  DATASET: ./data/datasets/samson_dataset.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  INIT: True
  BETA: 5000.0
  GAMMA: 3e-2
  COL: 95
  LR: 6e-3
  COSLR_RATE: 0.01
  DATASET: samson
  MODEL_NAME: cnn_vit
  DIM: 200
  EPOCH: 200
  L: 156
  ORDER_ABD: &id001
  - 0
  - 1
  - 2
  ORDER_ENDMEM: *id001
  P: 3
  PATCH: 5
  WEIGHT_DECAY_PARAM: 4.0e-05
