PATH:
  DATASET: ./data/datasets/samson_dataset.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  BETA: 5000.0
  COL: 95
  COSLR_RATE: 0.01
  DATASET: samson
  DIM: 60
  EPOCH: 400
  GAMMA: 0.03
  INIT: true
  L: 156
  LR: 0.016
  MODEL_NAME: swin_transformer
  ORDER_ABD:
  - 0
  - 1
  - 2
  ORDER_ENDMEM:
  - 0
  - 1
  - 2
  P: 3
  PATCH: 5
  WEIGHT_DECAY_PARAM: 4.0e-05
