PATH:
  DATASET: ./data/datasets/apex_dataset.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  BETA: 5000.0
  COL: 110
  DATASET: apex
  DIM: 60
  EPOCH: 600
  GAMMA: 0.001
  INIT: false
  COSLR_RATE: 0.3
  L: 285
  LR: 0.01
#  ORDER_ABD: &id001
#  - 0
#  - 1
#  - 3
#  - 2
#  ORDER_ENDMEM: *id001
  ORDER_ABD: &id001
    - 3
    - 1
    - 0
    - 2
  ORDER_ENDMEM: *id001
  P: 4
  PATCH: 5
  WEIGHT_DECAY_PARAM: 4.0e-05
