PATH:
  DATASET: ./data/datasets/apex_dataset.mat
  SAVE_DIR: ./runs/logs/
SYSTEM:
  DEVICE: cuda
TRAINING:
  BETA: 5000.0
  COL: 110
  COSLR_RATE: 0.3
  DATASET: apex
  DIM: 60
  EPOCH: 200
  GAMMA: 0.03
  INIT: true
  L: 285
  LR: 0.016
  MODEL_NAME: swin_transformer
  ORDER_ABD: &id001
  - 0
  - 1
  - 2
  - 3
  ORDER_ENDMEM: *id001
  P: 4
  PATCH: 5
  WEIGHT_DECAY_PARAM: 4.0e-05
